#!/bin/bash
mysql <<EOF
  GRANT ALL ON zabbix.* TO 'zabbix'@'localhost' IDENTIFIED BY 'zabbix';
  create database zabbix character set utf8 collate utf8_bin;
  use zabbix;
  source /usr/share/doc/zabbix-server-mysql-2.2.3/create/schema.sql;
  source /usr/share/doc/zabbix-server-mysql-2.2.3/create/images.sql;
  source /usr/share/doc/zabbix-server-mysql-2.2.3/create/data.sql;

EOF
zabbix_server -n `grep "NodeID=" /etc/zabbix/zabbix_server.conf | cut -d\= -f2` -c /etc/zabbix/zabbix_server.conf
